# Generated by Django 2.0.2 on 2018-03-04 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('loan_status', models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], default='a', help_text='Tool availability', max_length=1)),
                ('loan_duration', models.IntegerField(help_text='Loan duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the ad', primary_key=True, serialize=False)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a cateogry (e.g. Moving, Gardening etc.)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this tool', to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
    ]
