# Generated by Django 2.0.2 on 2018-03-06 03:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('loan_status', models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved')], default='a', help_text='Tool availability', max_length=1)),
                ('loan_duration', models.IntegerField(help_text='Loan duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the ad', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, choices=[('Other', 'Other'), ('Home Renovation', 'Home Renovation'), ('Gardening', 'Gardening'), ('Power Tools', 'Power Tools'), ('Moving', 'Moving'), ('Garage', 'Garage'), ('Washroom', 'Washroom')], default='Other', help_text='Choose a cateogry (e.g. Moving, Gardening etc.)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category'),
        ),
    ]
