# Generated by Django 2.0.2 on 2018-03-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Home Renovation', 'Home Renovation'), ('Gardening', 'Gardening'), ('Power Tools', 'Power Tools'), ('Moving', 'Moving'), ('Garage', 'Garage'), ('Washroom', 'Washroom')], default='Other', help_text='Choose a cateogry (e.g. Moving, Gardening etc.)', max_length=20, unique=True),
        ),
    ]
