# Generated by Django 2.0.2 on 2018-03-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180304_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, default='0', help_text='Choose a cateogry (e.g. Moving, Gardening etc.)', max_length=1),
        ),
    ]
