# Generated by Django 2.0.2 on 2018-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180304_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('0', 'Other'), ('1', 'Home Renovation'), ('2', 'Gardening'), ('3', 'Power Tools'), ('4', 'Moving'), ('5', 'Garage'), ('6', 'Washroom')], default='0', help_text='Choose a cateogry (e.g. Moving, Gardening etc.)', max_length=1),
        ),
    ]
