# Generated by Django 2.0.2 on 2018-03-13 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_ad_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
