# Generated by Django 2.0.2 on 2018-03-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_ad_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='poster',
            new_name='renter',
        ),
    ]
