# Generated by Django 2.0.2 on 2018-03-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180312_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
