# Generated by Django 2.0.2 on 2018-03-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180313_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='add_fav',
            field=models.BooleanField(default=False),
        ),
    ]
