# Generated by Django 2.0.2 on 2018-03-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180314_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('Home Renovation', 'Home Renovation'), ('Gardening', 'Gardening'), ('Power Tools', 'Power Tools'), ('Moving', 'Moving'), ('Garage', 'Garage'), ('Washroom', 'Washroom'), ('Kitchen', 'Kitchen'), ('Automobile', 'Automobile'), ('Other', 'Other')], default='Other', help_text='Choose a cateogry (e.g. Moving, Gardening etc.)', max_length=20, unique=True),
        ),
    ]
