# Generated by Django 2.0.2 on 2018-03-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180314_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_ads', to='profiles.Profile'),
        ),
    ]
