# Generated by Django 2.0.2 on 2018-03-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_favourites'),
        ('catalog', '0011_auto_20180315_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='add_requestor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='borrow_requests',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favs', to='profiles.Profile'),
        ),
    ]
