# Generated by Django 2.0.2 on 2018-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180315_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='add_requestor',
            field=models.BooleanField(default=False),
        ),
    ]
