# Generated by Django 2.0.2 on 2018-03-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180315_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_img',
            field=models.ImageField(blank=True, upload_to='ad_img'),
        ),
    ]
