# Generated by Django 2.0.2 on 2018-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_ad_ad_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_img',
            field=models.ImageField(blank=True, default='ad_images/no_img.png', upload_to='ad_images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='favourites',
            field=models.ManyToManyField(null=True, related_name='favs', to='profiles.Profile'),
        ),
    ]
