# Generated by Django 2.0.2 on 2018-03-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180318_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='add_fav',
        ),
    ]
