# Generated by Django 2.0.2 on 2018-03-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_ad_add_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_img',
            field=models.ImageField(blank=True, default='ad_images/no_img.png', null=True, upload_to='ad_images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='borrow_requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favs', to='profiles.Profile'),
        ),
    ]
