# Generated by Django 2.0.2 on 2018-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180318_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='borrow_requests',
            field=models.ManyToManyField(blank=True, related_name='borrow_requests', to='profiles.Profile'),
        ),
    ]
