# Generated by Django 2.0.2 on 2018-03-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180318_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('c', 'Completed')], default='a', help_text='Tool availability', max_length=1),
        ),
    ]
