# Generated by Django 2.0.2 on 2018-03-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_category_ad_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ad_img',
            new_name='category_img',
        ),
    ]
